-- This file is auto-generated by scripts/generate-seed.js
-- Run `npm run seed:generate` to refresh it.
-- The actual content will be replaced with real hashed credentials.

-- Demo users (hashed passwords)
INSERT INTO users (name, email, password_hash, salt, role) VALUES
('Admin User', 'admin@example.com', 'placeholder_hash', 'placeholder_salt', 'admin'),
('Regular User', 'user@example.com', 'placeholder_hash', 'placeholder_salt', 'user');

-- Sample posts (8 original articles)
INSERT INTO posts (title, slug, category, excerpt, content, image_url, author_id, published) VALUES
('React Hooks Explained for Beginners', 'react-hooks-beginners', 'React', 'Learn the fundamentals of React Hooks and how they simplify state and lifecycle management.', '...full content...', 'https://via.placeholder.com/800x400', 1, 1),
('Modern JavaScript Features', 'modern-js-features', 'JavaScript', 'Explore the latest JavaScript features like arrow functions, destructuring, spread, and more.', '...full content...', 'https://via.placeholder.com/800x400', 1, 1),
('CSS Flexbox Complete Guide', 'css-flexbox-guide', 'CSS', 'Master CSS Flexbox with practical examples and layouts.', '...full content...', 'https://via.placeholder.com/800x400', 1, 1),
('HTML Semantic Elements', 'html-semantic-elements', 'HTML', 'Understand the importance of semantic HTML for accessibility and SEO.', '...full content...', 'https://via.placeholder.com/800x400', 1, 1),
('Build REST API with Node.js', 'nodejs-rest-api', 'Node.js', 'Step-by-step guide to building a RESTful API with Node.js and Express.', '...full content...', 'https://via.placeholder.com/800x400', 1, 1),
('Python Beginner Roadmap', 'python-beginner-roadmap', 'Python', 'A structured roadmap for beginners to start learning Python programming.', '...full content...', 'https://via.placeholder.com/800x400', 1, 1),
('PHP + MySQL CRUD Tutorial', 'php-mysql-crud', 'PHP', 'Learn how to create a simple CRUD application using PHP and MySQL.', '...full content...', 'https://via.placeholder.com/800x400', 1, 1),
('SQL Database Basics', 'sql-database-basics', 'Database', 'An introduction to SQL and relational databases with common queries.', '...full content...', 'https://via.placeholder.com/800x400', 1, 1);
