name = "codesphere-worker"
main = "worker/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "coding_blog_db"
database_id = "56105386-dbab-4b14-b196-8c4cb019b6dd"
